### ISSUE TITLE
Does not work with subarrays

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/nblas#5]
~~A bug with Node.js is causing the offsets of subarrays to not be registered when using the following pattern~~ Below code does not work with subarrays because the `ArrayBuffer` offset is not taken into account:

```c++
v8::Local<v8::Float64Array> array = argument.As<v8::Float64Array>();
void *data = array->Buffer()->GetContents().Data();
double *x = static_cast<double*>(data);
```

This seems to be fixed by using the following hack:

```c++
v8::Local<v8::Float64Array> array = argument.As<v8::Float64Array>();
void *data = array->Buffer()->GetContents().Data();

size_t offset = array->ByteOffset();
size_t data_ptr = reinterpret_cast<size_t>(data);
data_ptr += offset;

double *x = reinterpret_cast<double*>(data_ptr);
```

However, it appears to be undefined behaviour in C++. Not sure if I should wait for Node.js to patch the bug or if I should incorporate above into the code.

Ping @metabench.

**Comment by metabench** [comment]
I'd hesitate to call the first example a 'pattern', no offence to its authors intended. It looks like it gets the contents of the underlying buffer, and may not be the right code to match the intention. It's a general area I'm unsure about though, and am asking others, including those who run node.js to consider, and to establish and document what the patterns are.

See https://github.com/nodejs/node/issues/8269

I'm hopeful that those with a thorough understanding of V8 and C++ can agree on what the best practice for this is. I've not yet tried the provided hack. If no-one else has done this yet, I suppose that by default it is best practice as well as being a hack.

**Comment by mateogianolio** [comment]
Searched the node repo for `GetContents()` occurrences and found a few interesting results, e.g. [this test binding for zlib](https://github.com/nodejs/node/blob/4c9b0bdf2f69299617489ba98bd9c5d2002f2daa/test/addons/zlib-binding/binding.cc):

```c++
auto buffer = view->Buffer();
auto contents = buffer->GetContents();
auto data = static_cast<unsigned char*>(contents.Data()) + byte_offset;

...

auto result = node::Buffer::Copy(info.GetIsolate(),
                                 reinterpret_cast<const char*>(buf),
                                 sizeof(buf) - stream.avail_out);
```

They cast the underlying buffer to `unsigned char*`, add the offset and then later in the code use `reinterpret_cast` so it might be acceptable to do like that.

**Comment by mateogianolio** [comment]
I got this to work:

```c++
void *data = array->Buffer()->GetContents().Data());
size_t offset = array->ByteOffset();
unsigned char* data_offset = static_cast<unsigned char*>(data + offset);
double *x = reinterpret_cast<double*>(data_offset);
```

**Comment by metabench** [comment]
The first line of that example does not have matching brackets. Having removed an extra bracket at the end, I also get a compilation error:

    error C2036: 'void *' : unknown size

on the line that corresponds with:

    unsigned char* data_offset = static_cast<unsigned char*>(data + offset);

**Comment by mateogianolio** [comment]
Wow that was sloppy pasting on my part, the `+ offset` should be outside of the cast. Edited the code above.

**Comment by metabench** [comment]
I took the last two lines of your corrected code and condensed it into:

    double *x = reinterpret_cast<double*>(static_cast<unsigned char*>(data) + offset);

I suggest that would be better as it does not leave the `unsigned char *data_offset` data structure in memory, what's your opinion on this, @mateogianolio?

**Comment by mateogianolio** [comment]
Looks good!

I'm going to update the code in this repo with the fix and submit a pull request.
