### ISSUE TITLE
rotmg.cc seems to incorrectly access the parameter named "param"

### ISSUE THREAD

**Issue by erikgerrits** [mateogianolio/nblas#7]
Hi Mateo, thanks for sharing this library!

I looked into your rotmg.cc file and see the following:
```c++
void drotmg(const v8::FunctionCallbackInfo<v8::Value>& info) {
    double *d1 = reinterpret_cast<double*>(GET_CONTENTS(info[0].As<v8::Float64Array>()));
    double *d2 = reinterpret_cast<double*>(GET_CONTENTS(info[1].As<v8::Float64Array>()));
    double *b1 = reinterpret_cast<double*>(GET_CONTENTS(info[2].As<v8::Float64Array>()));
    const double b2 = info[3]->NumberValue();
    double *param = reinterpret_cast<double*>(GET_CONTENTS(info[5].As<v8::Float64Array>()));
    cblas_drotmg(d1, d2, b1, b2, param);
}
```

I'm not 100% sure, but it seems to me that `info[5]` should be `info[4]`.

**Comment by mateogianolio** [comment]
Thanks for the kind words and for reporting the issue!

**Comment by erikgerrits** [comment]
I'm the one who should thank you for updating your code so quickly. I'm creating a TypeScript declaration file of nblas and planning to push it to DefinitelyTyped. If I find anything else, I'll notify you.
